Docker Compose version 3

version: "3"

services:
  webserver:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./websites:/usr/share/nginx/html/
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123!@#
    restart: always
    volumes:
      - db_vol:/var/lib/mysql

volumes:
 db_vol:
    
